# SPDX-License-Identifier: Apache-2.0
"""Property-based tests (Hypothesis) for the SQLite store round-trip and soft-delete.

Covers the design's *Store Round-Trip* correctness properties against the Phase-1
``SqliteStore`` backend, driving them with arbitrary valid ``MemoryRecord``s
generated by Hypothesis and a fresh temporary in-memory store per example:

* **Property 20: Round-trip fidelity** — ``add`` then ``get`` returns an equal
  record (modulo server-set fields). — **Validates: Requirements 2.1**
* **Property 21: Soft-delete invariant** — after ``soft_delete`` the record's
  ``status`` is ``DELETED`` and it remains retrievable by id. — **Validates:
  Requirements 2.2**

Generator constraints that keep round-trip equality well-defined for the SQLite
backend:

* Embeddings are drawn as ``float32``-width floats so the packed ``float32`` BLOB
  unpacks byte-for-byte (no precision loss vs. the original Python floats).
* Timestamps are timezone-aware UTC so the ISO-8601 serialize/parse cycle returns
  an equal ``datetime`` (``timezone.utc`` round-trips exactly).
* ``contradicts`` is left empty: the ``memory_contradictions`` table has foreign
  keys to ``memories``, so an isolated record cannot reference other ids. The
  contradicts round-trip is covered by the example tests in
  ``test_sqlite_store.py``.

The optional-Hypothesis pattern mirrors the other core property tests: when
Hypothesis is unavailable, example-based fallbacks still exercise both properties.
"""

from __future__ import annotations

import dataclasses
from datetime import datetime, timedelta, timezone

from memoryguard_core.models import (
    SCOPE_REF_REQUIRED,
    MemoryStatus,
    Scope,
    Sensitivity,
    SourceType,
    new_memory_record,
)
from memoryguard_core.store import SqliteStore

try:  # Hypothesis is optional; plain fallbacks below run when it is absent.
    from hypothesis import HealthCheck, given, settings
    from hypothesis import strategies as st

    HAVE_HYPOTHESIS = True
except ImportError:  # pragma: no cover - exercised only without hypothesis
    HAVE_HYPOTHESIS = False


# ---------------------------------------------------------------------------
# Generators
# ---------------------------------------------------------------------------


if HAVE_HYPOTHESIS:
    # Text that is non-empty after trimming (content / source_ref / scope_ref).
    _nonblank_text = st.text(min_size=1, max_size=120).filter(lambda s: s.strip() != "")

    # JSON-safe metadata values (round-trip exactly through json.dumps/loads).
    _json_scalar = st.one_of(
        st.none(),
        st.booleans(),
        st.integers(min_value=-(10**6), max_value=10**6),
        st.text(max_size=40),
    )
    _metadata = st.dictionaries(
        keys=st.text(min_size=1, max_size=20),
        values=_json_scalar,
        max_size=5,
    )
    _tags = st.lists(st.text(max_size=20), max_size=5)

    # float32-width values pack/unpack byte-for-byte in the embeddings BLOB.
    _embedding = st.one_of(
        st.none(),
        st.lists(
            st.floats(width=32, allow_nan=False, allow_infinity=False),
            min_size=1,
            max_size=12,
        ),
    )

    # Naive bounds + a UTC timezone strategy -> tz-aware UTC datetimes that
    # round-trip exactly through ISO-8601 serialization.
    _utc_datetimes = st.datetimes(
        min_value=datetime(2000, 1, 1),
        max_value=datetime(2100, 1, 1),
        timezones=st.just(timezone.utc),
    )

    @st.composite
    def memory_records(draw):
        """Draw an arbitrary valid :class:`MemoryRecord` via the factory."""

        scope = draw(st.sampled_from(list(Scope)))
        if scope in SCOPE_REF_REQUIRED:
            scope_ref = draw(_nonblank_text)
        else:
            scope_ref = draw(st.one_of(st.none(), _nonblank_text))

        created = draw(_utc_datetimes)
        # expires_at, when present, must be strictly after created_at.
        expires_at = draw(
            st.one_of(
                st.none(),
                st.integers(min_value=1, max_value=10**7).map(
                    lambda secs: created + timedelta(seconds=secs)
                ),
            )
        )

        return new_memory_record(
            content=draw(_nonblank_text),
            source_type=draw(st.sampled_from(list(SourceType))),
            source_ref=draw(_nonblank_text),
            scope=scope,
            scope_ref=scope_ref,
            expires_at=expires_at,
            trust_score=draw(
                st.floats(
                    min_value=0.0, max_value=1.0, allow_nan=False, allow_infinity=False
                )
            ),
            sensitivity=draw(st.sampled_from(list(Sensitivity))),
            status=draw(st.sampled_from(list(MemoryStatus))),
            tags=draw(_tags),
            confirmations=draw(st.integers(min_value=0, max_value=10**6)),
            embedding=draw(_embedding),
            metadata=draw(_metadata),
            now=created,
        )


# ---------------------------------------------------------------------------
# Property 20 — round-trip fidelity  (Requirements 2.1)
# ---------------------------------------------------------------------------


if HAVE_HYPOTHESIS:

    @settings(
        max_examples=200,
        deadline=None,
        suppress_health_check=[HealthCheck.too_slow],
    )
    @given(record=memory_records())
    def test_property_20_round_trip_fidelity(record):
        """**Validates: Requirements 2.1** — add(rec) then get(id) == rec.

        A fresh temporary in-memory store is used per example.
        """

        store = SqliteStore(":memory:")
        try:
            stored = store.add(record)
            assert store.get(stored.memory_id) == stored
        finally:
            store.close()


def test_property_20_round_trip_fidelity_fallback():
    """**Validates: Requirements 2.1** — example-based round-trip across field shapes."""

    examples = [
        dict(
            content="global plain record",
            source_type=SourceType.USER,
            source_ref="user://alice",
            scope=Scope.GLOBAL,
        ),
        dict(
            content="rich project record",
            source_type=SourceType.FILE,
            source_ref="repo://README.md@c123",
            scope=Scope.PROJECT,
            scope_ref="proj-1",
            trust_score=0.5,
            sensitivity=Sensitivity.SECRET,
            tags=["a", "b"],
            confirmations=4,
            embedding=[0.5, -0.25, 0.0, 0.75],  # float32-exact
            metadata={"k": "v", "n": 3},
            expires_at=datetime(2030, 1, 1, tzinfo=timezone.utc),
            now=datetime(2024, 1, 1, tzinfo=timezone.utc),
        ),
    ]
    for kwargs in examples:
        store = SqliteStore(":memory:")
        try:
            stored = store.add(new_memory_record(**kwargs))
            assert store.get(stored.memory_id) == stored
        finally:
            store.close()


# ---------------------------------------------------------------------------
# Property 21 — soft-delete invariant  (Requirements 2.2)
# ---------------------------------------------------------------------------


if HAVE_HYPOTHESIS:

    @settings(
        max_examples=200,
        deadline=None,
        suppress_health_check=[HealthCheck.too_slow],
    )
    @given(record=memory_records())
    def test_property_21_soft_delete_invariant(record):
        """**Validates: Requirements 2.2** — after soft_delete: status DELETED, still retrievable.

        Every other field is preserved (soft-delete only flips ``status``).
        """

        store = SqliteStore(":memory:")
        try:
            stored = store.add(record)
            store.soft_delete(stored.memory_id)
            fetched = store.get(stored.memory_id)
            assert fetched is not None
            assert fetched.status == MemoryStatus.DELETED
            assert fetched == dataclasses.replace(stored, status=MemoryStatus.DELETED)
        finally:
            store.close()


def test_property_21_soft_delete_invariant_fallback():
    """**Validates: Requirements 2.2** — example-based soft-delete invariant."""

    store = SqliteStore(":memory:")
    try:
        stored = store.add(
            new_memory_record(
                content="to be soft-deleted",
                source_type=SourceType.USER,
                source_ref="user://bob",
                scope=Scope.GLOBAL,
                status=MemoryStatus.ACTIVE,
            )
        )
        store.soft_delete(stored.memory_id)
        fetched = store.get(stored.memory_id)
        assert fetched is not None
        assert fetched.status == MemoryStatus.DELETED
        assert fetched == dataclasses.replace(stored, status=MemoryStatus.DELETED)
    finally:
        store.close()
