# SPDX-License-Identifier: Apache-2.0
<#
.SYNOPSIS
    Installs the MemoryGuard alpha wrapper command on Windows.

.DESCRIPTION
    Sets up a lightweight `memoryguard` wrapper for the public alpha. The wrapper
    calls `uv run --project <repo> memoryguard <args>`, so users do not need to
    remember `uv run` for daily use.

    Steps:
      1. Detects the MemoryGuard repo root (the directory containing pyproject.toml).
      2. Verifies `uv` is on PATH; otherwise prints install instructions and exits.
      3. Runs `uv sync --dev` to install Python dependencies (idempotent).
      4. Writes the wrapper script(s) under %LOCALAPPDATA%\Programs\MemoryGuard\.
      5. Reports whether that directory is on the user PATH and how to add it.

    This script is local-first and does not publish or install PyPI/npm packages.
#>

[CmdletBinding()]
param(
    [switch]$Force,
    [string]$InstallDir
)

$ErrorActionPreference = "Stop"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function Write-Ok {
    param([string]$Message)
    Write-Host "  [ok] $Message" -ForegroundColor Green
}

function Write-Warn {
    param([string]$Message)
    Write-Host "  [warn] $Message" -ForegroundColor Yellow
}

function Write-Err {
    param([string]$Message)
    Write-Host "  [error] $Message" -ForegroundColor Red
}

# ---------------------------------------------------------------------------
# Locate the MemoryGuard repo root
# ---------------------------------------------------------------------------

# $PSScriptRoot is the directory containing this installer script. The repo
# root is its parent (scripts/ is one level under the repo root).
$ScriptDir = $PSScriptRoot
if (-not $ScriptDir) {
    $ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
}

$RepoRoot = Resolve-Path -LiteralPath (Join-Path $ScriptDir "..") | Select-Object -ExpandProperty Path
$RepoRoot = (Resolve-Path -LiteralPath $RepoRoot).Path

$Pyproject = Join-Path $RepoRoot "pyproject.toml"
if (-not (Test-Path -LiteralPath $Pyproject)) {
    Write-Err "could not find pyproject.toml at $RepoRoot"
    Write-Err "Please run this script from inside the MemoryGuard repository."
    exit 1
}

Write-Step "MemoryGuard alpha installer"
Write-Host "  repo: $RepoRoot"

# ---------------------------------------------------------------------------
# Verify uv
# ---------------------------------------------------------------------------

$uv = Get-Command uv -ErrorAction SilentlyContinue
if (-not $uv) {
    Write-Err "uv is not on your PATH."
    Write-Host ""
    Write-Host "  Install uv first:"
    Write-Host "    irm https://astral.sh/uv/install.ps1 | iex"
    Write-Host ""
    Write-Host "  Then re-run:"
    Write-Host "    powershell -ExecutionPolicy Bypass -File scripts/install-alpha.ps1"
    exit 1
}
# PowerShell's Get-Command parses the version from FileVersionInfo, which
# is often empty for shim binaries. Ask uv directly for the canonical string.
$uvVersionOutput = & uv --version 2>$null
$uvVersion = if ($uvVersionOutput) { ($uvVersionOutput -split "\s+")[1] } else { "unknown" }
Write-Ok "uv $uvVersion found"

# ---------------------------------------------------------------------------
# Run uv sync --dev
# ---------------------------------------------------------------------------

Write-Step "Running uv sync --dev (this may take a moment on first run)"
Push-Location -LiteralPath $RepoRoot
try {
    & uv sync --dev
    if ($LASTEXITCODE -ne 0) {
        Write-Err "uv sync --dev failed (exit $LASTEXITCODE)."
        exit $LASTEXITCODE
    }
}
finally {
    Pop-Location
}
Write-Ok "Python dependencies installed"

# ---------------------------------------------------------------------------
# Write the wrapper
# ---------------------------------------------------------------------------

if (-not $InstallDir) {
    $InstallDir = Join-Path $env:LOCALAPPDATA "Programs\MemoryGuard"
}

$RepoRootEscaped = $RepoRoot -replace "'", "''"

$Ps1Content = @"
# MemoryGuard alpha wrapper (auto-generated by scripts/install-alpha.ps1).
# This file is safe to delete; the matching uninstaller is scripts/uninstall-alpha.ps1.
`$ErrorActionPreference = "Stop"
`$repoRoot = '$RepoRootEscaped'
& uv run --project "`$repoRoot" memoryguard @args
exit `$LASTEXITCODE
"@

$CmdContent = @"
@echo off
REM MemoryGuard alpha wrapper (auto-generated by scripts/install-alpha.ps1).
REM This file is safe to delete; the matching uninstaller is scripts/uninstall-alpha.ps1.
"uv" run --project "$RepoRootEscaped" memoryguard %*
exit /b %ERRORLEVEL%
"@

New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null

$Ps1Path = Join-Path $InstallDir "memoryguard.ps1"
$CmdPath = Join-Path $InstallDir "memoryguard.cmd"

# Force re-write so reinstalls stay in sync with the repo path.
Set-Content -LiteralPath $Ps1Path -Value $Ps1Content -Encoding UTF8
Write-Ok "wrote $Ps1Path"

# .cmd files are consumed by cmd.exe. Use the system's default text encoding
# (no BOM) so the leading `@echo off` is not prepended with a UTF-8 byte
# order mark that cmd.exe would echo as garbage.
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($CmdPath, $CmdContent, $utf8NoBom)
Write-Ok "wrote $CmdPath (cmd.exe compatible)"

# ---------------------------------------------------------------------------
# PATH guidance
# ---------------------------------------------------------------------------

Write-Step "PATH"
$userPath = [Environment]::GetEnvironmentVariable("Path", "User")
$onPath = $false
if ($userPath) {
    $parts = $userPath -split ";"
    $onPath = $parts | Where-Object { $_ -ieq $InstallDir } | Select-Object -First 1
}
if ($onPath) {
    Write-Ok "$InstallDir is already on your user PATH"
} else {
    Write-Warn "$InstallDir is not on your user PATH"
    Write-Host ""
    Write-Host "  Add it to your user PATH for this PowerShell session:"
    Write-Host "    `$env:Path = `"$InstallDir;`$env:Path`""
    Write-Host ""
    Write-Host "  Add it permanently (re-open your shell afterwards):"
    Write-Host "    [Environment]::SetEnvironmentVariable('Path', `"$InstallDir;`$([Environment]::GetEnvironmentVariable('Path','User'))`", 'User')"
}

# ---------------------------------------------------------------------------
# Smoke test
# ---------------------------------------------------------------------------

Write-Step "Smoke test"
$probe = & uv run --project $RepoRoot memoryguard --help 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Err "uv run memoryguard --help failed; the wrapper will not work."
    Write-Host $probe
    exit $LASTEXITCODE
}
Write-Ok "uv run memoryguard --help responds"

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------

Write-Step "Installed"
Write-Host "  Try it:"
Write-Host ""
Write-Host "    memoryguard --help" -ForegroundColor White
Write-Host "    memoryguard demo" -ForegroundColor White
Write-Host "    memoryguard doctor" -ForegroundColor White
Write-Host ""
Write-Host "  To remove the wrapper later, run:"
Write-Host "    powershell -ExecutionPolicy Bypass -File scripts/uninstall-alpha.ps1"
