#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Installs the MemoryGuard alpha wrapper command on macOS or Linux.
#
# Sets up a lightweight `memoryguard` wrapper for the public alpha. The wrapper
# calls `uv run --project <repo> memoryguard <args>`, so users do not need to
# remember `uv run` for daily use.
#
# Steps:
#   1. Detects the MemoryGuard repo root (the directory containing pyproject.toml).
#   2. Verifies `uv` is on PATH; otherwise prints install instructions and exits.
#   3. Runs `uv sync --dev` to install Python dependencies (idempotent).
#   4. Writes ~/.local/bin/memoryguard and marks it executable.
#   5. Reports whether ~/.local/bin is on the user PATH and how to add it.
#
# This script is local-first and does not publish or install PyPI/npm packages.

set -euo pipefail

FORCE=0
if [[ "${1:-}" == "--force" || "${1:-}" == "-f" ]]; then
    FORCE=1
fi

# ---------------------------------------------------------------------------
# Locate the MemoryGuard repo root
# ---------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

if [[ ! -f "$REPO_ROOT/pyproject.toml" ]]; then
    echo "  [error] could not find pyproject.toml at $REPO_ROOT" >&2
    echo "  Please run this script from inside the MemoryGuard repository." >&2
    exit 1
fi

# Stable absolute path so the wrapper works even if the repo is moved later
# (re-run the installer to repoint the wrapper at the new location).
REPO_ROOT="$(cd "$REPO_ROOT" && pwd)"

echo
echo "==> MemoryGuard alpha installer"
echo "  repo: $REPO_ROOT"

# ---------------------------------------------------------------------------
# Verify uv
# ---------------------------------------------------------------------------

if ! command -v uv >/dev/null 2>&1; then
    echo
    echo "  [error] uv is not on your PATH." >&2
    echo
    echo "  Install uv first:" >&2
    echo "    curl -LsSf https://astral.sh/uv/install.sh | sh" >&2
    echo
    echo "  Then re-run:" >&2
    echo "    bash scripts/install-alpha.sh" >&2
    exit 1
fi
echo "  [ok] uv $(uv --version) found"

# ---------------------------------------------------------------------------
# Run uv sync --dev
# ---------------------------------------------------------------------------

echo
echo "==> Running uv sync --dev (this may take a moment on first run)"
(
    cd "$REPO_ROOT"
    uv sync --dev
)
echo "  [ok] Python dependencies installed"

# ---------------------------------------------------------------------------
# Write the wrapper
# ---------------------------------------------------------------------------

INSTALL_DIR="${MEMORYGUARD_INSTALL_DIR:-$HOME/.local/bin}"
WRAPPER="$INSTALL_DIR/memoryguard"

mkdir -p "$INSTALL_DIR"

cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# MemoryGuard alpha wrapper (auto-generated by scripts/install-alpha.sh).
# This file is safe to delete; the matching uninstaller is scripts/uninstall-alpha.sh.
set -e
exec uv run --project "$REPO_ROOT" memoryguard "\$@"
EOF

chmod +x "$WRAPPER"
echo "  [ok] wrote $WRAPPER"

# ---------------------------------------------------------------------------
# PATH guidance
# ---------------------------------------------------------------------------

echo
echo "==> PATH"

case ":${PATH}:" in
    *":$INSTALL_DIR:"*)
        echo "  [ok] $INSTALL_DIR is already on your PATH"
        ;;
    *)
        echo "  [warn] $INSTALL_DIR is not on your PATH"
        echo
        echo "  Add it for this shell session:"
        echo "    export PATH=\"$INSTALL_DIR:\$PATH\""
        echo
        echo "  Add it permanently (e.g. in ~/.bashrc, ~/.zshrc, or ~/.profile):"
        echo "    echo 'export PATH=\"$INSTALL_DIR:\$PATH\"' >> ~/.bashrc"
        echo
        if [[ -n "${BASH_VERSION:-}" ]]; then
            if [[ -f "$HOME/.bashrc" ]]; then
                echo "  Detected ~/.bashrc — a one-shot command you can paste:"
                echo "    echo 'export PATH=\"$INSTALL_DIR:\$PATH\"' >> ~/.bashrc && source ~/.bashrc"
            fi
        fi
        ;;
esac

# ---------------------------------------------------------------------------
# Smoke test
# ---------------------------------------------------------------------------

echo
echo "==> Smoke test"
if ! (cd "$REPO_ROOT" && uv run memoryguard --help >/dev/null 2>&1); then
    echo "  [error] uv run memoryguard --help failed; the wrapper will not work." >&2
    exit 1
fi
echo "  [ok] uv run memoryguard --help responds"

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------

echo
echo "==> Installed"
echo
echo "  Try it:"
echo
echo "    memoryguard --help"
echo "    memoryguard demo"
echo "    memoryguard doctor"
echo
echo "  To remove the wrapper later, run:"
echo "    bash scripts/uninstall-alpha.sh"
