# SPDX-License-Identifier: Apache-2.0
"""Local context-file generation for AI coding agents.

Context Sync turns MemoryGuard's trusted local memories plus lightweight repo
metadata into agent-readable files such as ``AGENTS.md`` and ``CLAUDE.md``.
The implementation is deterministic, standard-library only, and never calls a
network service or external LLM.
"""

from __future__ import annotations

import difflib
import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, Optional

from memoryguard_core.decisions import canonical_decision_label, extract_decision
from memoryguard_core.models import MemoryRecord, MemoryStatus, Sensitivity
from memoryguard_core.secrets import contains_secret, redact_text
from memoryguard_core.store.base import MemoryStore

__all__ = [
    "CONTEXT_FILES",
    "ContextFilePlan",
    "ContextSyncPlan",
    "ContextSyncStatus",
    "approve_context_sync",
    "build_context_sync_plan",
    "context_status",
    "format_unified_diff",
    "write_pending_context_plan",
]

CONTEXT_FILES: tuple[str, ...] = (
    "AGENTS.md",
    "CLAUDE.md",
    "MEMORY.md",
    ".cursor/rules/memoryguard.mdc",
)

PENDING_DIR = ".memoryguard/context-sync"
PENDING_FILE = "pending.json"
STATE_FILE = "state.json"

START_MARKER = "<!-- memoryguard:context:start -->"
END_MARKER = "<!-- memoryguard:context:end -->"
HEADER = (
    f"{START_MARKER}\n"
    "<!-- Generated by MemoryGuard Context Sync. Edit MemoryGuard memories or "
    "repo metadata, then rerun context update. -->\n"
)
FOOTER = f"{END_MARKER}\n"

@dataclass(frozen=True)
class ContextFilePlan:
    """Planned content update for one generated context file."""

    path: str
    current: str
    proposed: str

    @property
    def changed(self) -> bool:
        return self.current != self.proposed


@dataclass(frozen=True)
class ContextSyncPlan:
    """A full context-sync plan across all target files."""

    root: Path
    files: tuple[ContextFilePlan, ...]
    generated_at: datetime

    @property
    def changed_files(self) -> tuple[ContextFilePlan, ...]:
        return tuple(item for item in self.files if item.changed)

    @property
    def has_changes(self) -> bool:
        return bool(self.changed_files)


@dataclass(frozen=True)
class ContextSyncStatus:
    """Dashboard-friendly state for Context Sync."""

    files: tuple[dict, ...]
    last_sync_time: Optional[str]
    pending_diff: str
    pending_files: tuple[str, ...]


def build_context_sync_plan(root: Path, store: MemoryStore) -> ContextSyncPlan:
    """Build a deterministic update plan from memories + repo metadata."""

    root = root.expanduser().resolve()
    generated_at = datetime.now(timezone.utc)
    body = _render_body(root, store, generated_at)
    files = tuple(_plan_file(root, rel_path, body) for rel_path in CONTEXT_FILES)
    return ContextSyncPlan(root=root, files=files, generated_at=generated_at)


def write_pending_context_plan(plan: ContextSyncPlan) -> None:
    """Persist a pending plan for later ``context approve`` or dashboard apply."""

    pending = _pending_path(plan.root)
    pending.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "generated_at": plan.generated_at.isoformat(),
        "files": [
            {
                "path": item.path,
                "current": item.current,
                "proposed": item.proposed,
            }
            for item in plan.files
        ],
    }
    pending.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def approve_context_sync(root: Path) -> tuple[int, tuple[str, ...]]:
    """Apply the pending context plan and record sync state."""

    root = root.expanduser().resolve()
    plan = _read_pending(root)
    written: list[str] = []
    for item in plan.files:
        if not item.changed:
            continue
        target = root / item.path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(item.proposed, encoding="utf-8")
        written.append(item.path)

    pending = _pending_path(root)
    if pending.exists():
        pending.unlink()
    _write_state(root, plan.generated_at)
    return len(written), tuple(written)


def context_status(root: Path, store: MemoryStore) -> ContextSyncStatus:
    """Return generated files, last sync time, and any saved pending diff."""

    root = root.expanduser().resolve()
    pending_plan = _try_read_pending(root)
    _ = store  # Kept in the signature so callers share the same local dependency shape.
    diff = format_unified_diff(pending_plan) if pending_plan else ""
    pending_files = tuple(item.path for item in pending_plan.changed_files) if pending_plan else ()
    state = _read_state(root)
    files = []
    for rel_path in CONTEXT_FILES:
        target = root / rel_path
        files.append(
            {
                "path": rel_path,
                "exists": target.is_file(),
                "managed": _has_managed_block(target.read_text(encoding="utf-8"))
                if target.is_file()
                else False,
                "size": target.stat().st_size if target.is_file() else 0,
            }
        )
    return ContextSyncStatus(
        files=tuple(files),
        last_sync_time=state.get("last_sync_time"),
        pending_diff=diff,
        pending_files=pending_files,
    )


def format_unified_diff(plan: ContextSyncPlan) -> str:
    """Render a unified diff for changed files in ``plan``."""

    chunks: list[str] = []
    for item in plan.changed_files:
        old = item.current.splitlines(keepends=True)
        new = item.proposed.splitlines(keepends=True)
        chunks.extend(
            difflib.unified_diff(
                old,
                new,
                fromfile=f"a/{item.path}",
                tofile=f"b/{item.path}",
                lineterm="",
            )
        )
        chunks.append("")
    return "\n".join(chunks).rstrip() + ("\n" if chunks else "")


def _plan_file(root: Path, rel_path: str, body: str) -> ContextFilePlan:
    target = root / rel_path
    current = target.read_text(encoding="utf-8") if target.is_file() else ""
    proposed_block = HEADER + body + FOOTER
    if current:
        proposed = _replace_or_append_block(current, proposed_block)
    else:
        proposed = proposed_block
    return ContextFilePlan(path=rel_path, current=current, proposed=proposed)


def _replace_or_append_block(current: str, block: str) -> str:
    start = current.find(START_MARKER)
    end = current.find(END_MARKER)
    if start != -1 and end != -1 and end > start:
        end += len(END_MARKER)
        suffix = current[end:]
        if suffix.startswith("\r\n"):
            suffix = suffix[2:]
        elif suffix.startswith("\n"):
            suffix = suffix[1:]
        return current[:start] + block + suffix
    separator = "" if current.endswith("\n") else "\n"
    return f"{current}{separator}\n{block}"


def _has_managed_block(text: str) -> bool:
    return START_MARKER in text and END_MARKER in text


def _render_body(root: Path, store: MemoryStore, generated_at: datetime) -> str:
    metadata = _scan_repo(root)
    records = store.list()
    records_by_id = {record.memory_id: record for record in records}
    active, deprecated, avoid, omitted_sensitive = _classify_memories(records)
    important = _memory_lines(active, records_by_id) + _sensitive_notes(omitted_sensitive)
    sections = [
        ("Project Overview", _project_overview(metadata, active, records_by_id)),
        ("Tech Stack", _tech_stack(metadata, active, records_by_id)),
        ("Commands", _commands(metadata, active, records_by_id)),
        ("Architecture", _architecture(metadata, active, records_by_id)),
        ("Coding Rules", _coding_rules(active, records_by_id)),
        (
            "Important Decisions",
            important or ["No active MemoryGuard decisions yet."],
        ),
        (
            "Deprecated/Outdated Decisions",
            _memory_lines(deprecated, records_by_id) or ["None recorded."],
        ),
        ("Things Agents Must Avoid", _avoid_lines(avoid, records_by_id)),
    ]
    lines = [
        "# MemoryGuard Context",
        "",
        f"Generated: {generated_at.isoformat()}",
        "",
    ]
    for title, items in sections:
        lines.extend([f"## {title}", ""])
        for item in items[:24]:
            lines.append(f"- {_redact(item)}")
        lines.append("")
    return "\n".join(lines)


@dataclass
class RepoMetadata:
    name: str
    overview: str = ""
    tech_stack: list[str] = field(default_factory=list)
    commands: list[str] = field(default_factory=list)
    architecture: list[str] = field(default_factory=list)


def _scan_repo(root: Path) -> RepoMetadata:
    meta = RepoMetadata(name=root.name)
    readme = _read_first_existing(root, ("README.md", "readme.md"))
    if readme:
        meta.overview = _first_paragraph(readme)
        meta.commands.extend(_extract_fenced_commands(readme))

    for filename in ("package.json", "pyproject.toml", "pnpm-workspace.yaml", "turbo.json"):
        path = root / filename
        if path.is_file():
            _read_metadata_file(path, meta)

    for docs_name in ("docs/architecture.md", "docs/getting-started.md", "CONTRIBUTING.md"):
        path = root / docs_name
        if path.is_file():
            text = _safe_read(path)
            if text:
                para = _first_paragraph(text)
                if para:
                    meta.architecture.append(f"{docs_name}: {para}")
                meta.commands.extend(_extract_fenced_commands(text))
    meta.commands = _dedupe(meta.commands)[:18]
    meta.tech_stack = _dedupe(meta.tech_stack)
    meta.architecture = _dedupe(meta.architecture)[:12]
    return meta


def _read_metadata_file(path: Path, meta: RepoMetadata) -> None:
    text = _safe_read(path)
    if not text:
        return
    name = path.name
    if name == "package.json":
        try:
            data = json.loads(text)
        except json.JSONDecodeError:
            data = {}
        package_name = data.get("name")
        if package_name:
            meta.name = str(package_name)
        scripts = data.get("scripts") if isinstance(data, dict) else None
        if isinstance(scripts, dict):
            for script_name in ("dev", "build", "test", "lint"):
                if script_name in scripts:
                    meta.commands.append(f"pnpm {script_name}")
        deps = {}
        for key in ("dependencies", "devDependencies"):
            if isinstance(data.get(key), dict):
                deps.update(data[key])
        for dep in ("react", "next", "vite", "typescript", "turbo"):
            if dep in deps:
                meta.tech_stack.append(dep)
    elif name == "pyproject.toml":
        meta.tech_stack.append("Python")
        if "typer" in text.lower():
            meta.tech_stack.append("Typer CLI")
        if "fastapi" in text.lower():
            meta.tech_stack.append("FastAPI")
        if "pytest" in text.lower():
            meta.commands.append("uv run pytest")
        if "ruff" in text.lower():
            meta.commands.append("uv run ruff check .")
    elif name == "pnpm-workspace.yaml":
        meta.tech_stack.append("pnpm workspace")
    elif name == "turbo.json":
        meta.tech_stack.append("Turborepo")


def _read_first_existing(root: Path, names: Iterable[str]) -> str:
    for name in names:
        path = root / name
        if path.is_file():
            return _safe_read(path)
    return ""


def _safe_read(path: Path, limit: int = 80_000) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")[:limit]
    except OSError:
        return ""


def _first_paragraph(text: str) -> str:
    cleaned = []
    in_code = False
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("```"):
            in_code = not in_code
            continue
        if in_code or not stripped or stripped.startswith("<") or stripped.startswith("!["):
            if cleaned:
                break
            continue
        if stripped.startswith("#"):
            continue
        cleaned.append(stripped)
    return redact_text(" ".join(cleaned))[:500]


def _extract_fenced_commands(text: str) -> list[str]:
    commands: list[str] = []
    in_block = False
    for raw in text.splitlines():
        line = raw.strip()
        if line.startswith("```"):
            in_block = not in_block
            continue
        if not in_block:
            continue
        line = line.removeprefix("$").strip()
        if line.startswith(("uv ", "pnpm ", "npm ", "yarn ", "python ", "pytest ", "ruff ")):
            commands.append(redact_text(line))
    return commands


def _classify_memories(
    records: Iterable[MemoryRecord],
) -> tuple[list[MemoryRecord], list[MemoryRecord], list[MemoryRecord], list[MemoryRecord]]:
    omitted_sensitive = [
        r
        for r in records
        if r.status != MemoryStatus.DELETED
        and (r.sensitivity in {Sensitivity.SECRET, Sensitivity.PII} or contains_secret(r.content))
    ]
    usable = [
        r
        for r in records
        if r.status != MemoryStatus.DELETED
        and r.sensitivity not in {Sensitivity.SECRET, Sensitivity.PII}
        and not contains_secret(r.content)
    ]
    active = [r for r in usable if r.status == MemoryStatus.ACTIVE]
    deprecated = [
        r
        for r in usable
        if r.status
        in {
            MemoryStatus.CORRECTED,
            MemoryStatus.EXPIRED,
            MemoryStatus.DISPUTED,
            MemoryStatus.SUPERSEDED,
            MemoryStatus.OUTDATED,
        }
        or _has_any(r.content, ("deprecated", "outdated", "superseded", "do not use"))
    ]
    avoid = [
        r
        for r in usable
        if _has_any(r.content, ("avoid", "never", "do not", "don't", "must not", "deprecated"))
    ]
    return active, deprecated, avoid, omitted_sensitive


def _project_overview(
    meta: RepoMetadata, active: list[MemoryRecord], records_by_id: dict[str, MemoryRecord]
) -> list[str]:
    items = [meta.overview or f"{meta.name} project."]
    for record in active:
        if _has_any(record.content, ("project", "product", "overview", "memoryguard")):
            items.append(_memory_line(record, records_by_id))
    return _dedupe(items)


def _tech_stack(
    meta: RepoMetadata, active: list[MemoryRecord], records_by_id: dict[str, MemoryRecord]
) -> list[str]:
    items = list(meta.tech_stack)
    tech_keys = {
        "backend_framework",
        "package_manager",
        "database",
        "database_local",
        "database_cloud",
        "frontend_framework",
        "deployment_target",
    }
    for record in active:
        decision = extract_decision(record.content)
        if decision is not None and decision.key in tech_keys:
            items.append(_memory_line(record, records_by_id))
    return _dedupe(items) or ["Unknown. Add or ingest project metadata."]


def _commands(
    meta: RepoMetadata, active: list[MemoryRecord], records_by_id: dict[str, MemoryRecord]
) -> list[str]:
    items = list(meta.commands)
    for record in active:
        decision = extract_decision(record.content)
        if decision is not None and decision.key == "test_command":
            items.append(_memory_line(record, records_by_id))
    return _dedupe(items) or ["Run the project-specific checks documented in README.md."]


def _architecture(
    meta: RepoMetadata, active: list[MemoryRecord], records_by_id: dict[str, MemoryRecord]
) -> list[str]:
    items = list(meta.architecture)
    architecture_keys = {
        "backend_framework",
        "database",
        "database_local",
        "database_cloud",
        "frontend_framework",
        "deployment_target",
    }
    for record in active:
        decision = extract_decision(record.content)
        if (
            _has_any(record.content, ("architecture", "package", "module", "api", "dashboard", "cli"))
            or (decision is not None and decision.key in architecture_keys)
        ):
            items.append(_memory_line(record, records_by_id))
    return _dedupe(items) or ["No architecture notes recorded yet."]


def _coding_rules(active: list[MemoryRecord], records_by_id: dict[str, MemoryRecord]) -> list[str]:
    rules = []
    for record in active:
        decision = extract_decision(record.content)
        if (
            _has_any(record.content, ("use ", "prefer", "must", "should", "rule", "test", "lint"))
            and (decision is None or decision.key not in {"package_manager", "test_command"})
        ):
            rules.append(_memory_line(record, records_by_id))
    return _dedupe(rules) or ["Follow existing repository patterns and keep changes local-first."]


def _avoid_lines(records: list[MemoryRecord], records_by_id: dict[str, MemoryRecord]) -> list[str]:
    return _memory_lines(records, records_by_id) or [
        "Do not introduce external LLM/API dependencies into OSS local runtime paths.",
        "Do not store raw chat logs or secret values in generated context files.",
        "Do not cross the documented open-core boundary from OSS packages into commercial packages.",
    ]


def _memory_lines(records: list[MemoryRecord], records_by_id: dict[str, MemoryRecord]) -> list[str]:
    return [_memory_line(record, records_by_id) for record in records[:24]]


def _memory_line(record: MemoryRecord, records_by_id: dict[str, MemoryRecord]) -> str:
    source_ref = redact_text(record.source_ref) if record.source_ref else ""
    source = f" (source: {source_ref})" if source_ref else ""
    decision = extract_decision(record.content)
    if decision is not None:
        label = canonical_decision_label(decision.key)
        if record.status == MemoryStatus.SUPERSEDED:
            newer_value = _superseding_decision_value(record, records_by_id)
            if newer_value:
                return (
                    f"{label} was previously {redact_text(decision.value)}; "
                    f"superseded by {redact_text(newer_value)}.{source}"
                )
            return f"{label} was previously {_redact(decision.value)}; superseded.{source}"
        if record.status == MemoryStatus.OUTDATED:
            return f"{label} was previously {redact_text(decision.value)}; outdated.{source}"
        return f"{label}: {redact_text(decision.value)}{source}"

    suffix = ""
    if record.status == MemoryStatus.SUPERSEDED:
        superseded_by = record.metadata.get("superseded_by")
        suffix = f" [superseded by {superseded_by}]" if superseded_by else " [superseded]"
    elif record.status == MemoryStatus.OUTDATED:
        suffix = " [outdated]"
    return f"{redact_text(record.content)}{source}{suffix}"


def _sensitive_notes(records: list[MemoryRecord]) -> list[str]:
    notes = []
    for record in records:
        source_ref = redact_text(record.source_ref) if record.source_ref else ""
        source = f" (source: {source_ref})" if source_ref else ""
        notes.append(f"Sensitive memory omitted from generated context.{source}")
    return _dedupe(notes)


def _superseding_decision_value(
    record: MemoryRecord, records_by_id: dict[str, MemoryRecord]
) -> Optional[str]:
    record_decision = extract_decision(record.content)
    if record_decision is not None and record_decision.key == "database":
        split_values: list[str] = []
        for other in records_by_id.values():
            if other.status != MemoryStatus.ACTIVE:
                continue
            decision = extract_decision(other.content)
            if decision is None:
                continue
            if decision.key == "database_local":
                split_values.append(f"local {decision.value}")
            elif decision.key == "database_cloud":
                split_values.append(f"cloud {decision.value}")
        if split_values:
            return " and ".join(_dedupe(split_values))

    superseded_by = record.metadata.get("superseded_by")
    if not isinstance(superseded_by, str):
        return None
    newer = records_by_id.get(superseded_by)
    if newer is None:
        return None
    decision = extract_decision(newer.content)
    return decision.value if decision is not None else None


def _has_any(text: str, needles: tuple[str, ...]) -> bool:
    lowered = text.lower()
    return any(needle in lowered for needle in needles)


def _dedupe(items: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for item in items:
        cleaned = " ".join(str(item).split())
        if not cleaned:
            continue
        key = cleaned.lower()
        if key in seen:
            continue
        seen.add(key)
        result.append(cleaned)
    return result


def _redact(text: str) -> str:
    return redact_text(text)


def _pending_path(root: Path) -> Path:
    return root / PENDING_DIR / PENDING_FILE


def _state_path(root: Path) -> Path:
    return root / PENDING_DIR / STATE_FILE


def _read_pending(root: Path) -> ContextSyncPlan:
    pending = _pending_path(root)
    if not pending.is_file():
        raise FileNotFoundError("no pending MemoryGuard context sync approval")
    data = json.loads(pending.read_text(encoding="utf-8"))
    return _plan_from_json(root, data)


def _try_read_pending(root: Path) -> Optional[ContextSyncPlan]:
    try:
        return _read_pending(root)
    except (FileNotFoundError, json.JSONDecodeError, KeyError, TypeError, ValueError):
        return None


def _plan_from_json(root: Path, data: dict) -> ContextSyncPlan:
    generated_at = datetime.fromisoformat(str(data["generated_at"]))
    files = tuple(
        ContextFilePlan(
            path=str(item["path"]),
            current=str(item.get("current", "")),
            proposed=str(item.get("proposed", "")),
        )
        for item in data.get("files", [])
    )
    return ContextSyncPlan(root=root.expanduser().resolve(), files=files, generated_at=generated_at)


def _write_state(root: Path, synced_at: datetime) -> None:
    state = _state_path(root)
    state.parent.mkdir(parents=True, exist_ok=True)
    state.write_text(
        json.dumps({"last_sync_time": synced_at.isoformat()}, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def _read_state(root: Path) -> dict:
    state = _state_path(root)
    if not state.is_file():
        return {}
    try:
        return json.loads(state.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
